# docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
# docker build $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_PIPELINE_ID-$1 .
# docker push $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_PIPELINE_ID-$1
# docker rmi $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_PIPELINE_ID-$1

docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
docker build $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_PIPELINE_ID-$1 .
docker push $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_PIPELINE_ID-$1
docker rmi $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_PIPELINE_ID-$1