apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-certs-%s" .Values.api.name .Values.deployment.environment }}
type: Opaque
data:
  cert.pem: {{ .Values.secrets.cert_pem }} 
  key.pem: {{ .Values.secrets.key_pem }} 
